version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disables security for easy local development
    ports:
      - "9200:9200" # Exposes Elasticsearch on localhost:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: